#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
QEL Indexer — mantiene y actualiza los índices de Semillas y Rutas.

- Idempotente: sólo escribe dentro de bloques AUTO.
- No rompe edición manual: todo fuera de AUTO queda intacto.
- Crea los índices si faltan (con metadatos QEL).
- Opcionalmente valida anchors de rutas.

Uso típico:
  python3 scripts/qel_indexer.py --file docs/core/QEL_Manual_Operativo.md --file docs/core/QEL_Libro_Sombras.md
  python3 scripts/qel_indexer.py --all

Integración (ejemplo):
  # En qel_promote_mac.sh (después de calcular HASH10, antes del commit):
  python3 scripts/qel_indexer.py --file "$FILE" --update seeds,routes --indices-dir docs/core/indices --seedI "$SEED" || \
    echo "[indexer] aviso: no se pudo actualizar (no fatal)" >&2
"""

import os, re, sys, argparse, datetime, unicodedata, glob, textwrap, pathlib

INDEX_DIR_DEFAULT = "docs/core/indices"
SEEDS_INDEX_BASENAME = "QEL_Index_Semillas_v1.0.md"
ROUTES_INDEX_BASENAME = "QEL_Index_Rutas_v1.0.md"

AUTO_SEEDS_BEGIN = "<!-- BEGIN:AUTO-SEEDS -->"
AUTO_SEEDS_END   = "<!-- END:AUTO-SEEDS -->"
AUTO_ROUTES_BEGIN = "<!-- BEGIN:AUTO-ROUTES -->"
AUTO_ROUTES_END   = "<!-- END:AUTO-ROUTES -->"

SEEDI_ENV_KEYS = ["QEL_SEEDI", "QEL_SEED", "SEEDI"]

def today_iso():
    return datetime.date.today().isoformat()

def read_text(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read()

def write_text(path, txt):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(txt)

def slugify(s: str) -> str:
    s = s.strip().lower()
    s = unicodedata.normalize("NFD", s)
    s = "".join(ch for ch in s if unicodedata.category(ch) != "Mn")
    s = re.sub(r"[^\w\s\-\.]", "", s, flags=re.U)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-{2,}", "-", s)
    return s

META_RE = re.compile(r"^(?P<k>cue|SeedI|SoT|Version|Updated)\s*[:=]\s*(?P<v>.+?)\s*$", re.I | re.M)

def extract_meta(text):
    meta = {}
    for m in META_RE.finditer(text):
        k = m.group("k")
        v = m.group("v").strip().strip('"').strip("'")
        meta[k] = v
    if "cue" not in meta:
        m = re.search(r"^\[QEL::ECO[^\]]+\]", text, re.M)
        if m:
            meta["cue"] = m.group(0)
    return meta

def extract_seedi_from_text(text):
    meta = extract_meta(text)
    return meta.get("SeedI")

SEED_PATTERN = re.compile(r"»\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9_\-]+)")

DEST_CANDIDATES = {
    "vf": "VF",
    "glosario": "Glosario",
    "atlas": "Atlas",
    "manual": "Manual",
    "sombras": "Sombras",
    "libro de sombras": "Sombras",
    "cue": "CUE",
    "rutas": "Atlas",
}

def guess_destination_from_line(line: str) -> str:
    # 1) Si hay flecha →, toma el texto a la derecha y busca un destino conocido
    if "→" in line:
        rhs = line.split("→", 1)[1].strip()
        rhs = rhs.split("|")[0].split("::")[-1].strip()
        rhs_low = slugify(rhs)
        for k, v in DEST_CANDIDATES.items():
            if k in rhs_low:
                return v
    # 2) Si hay " :: Destino :: ", usa el último segmento conocido
    if "::" in line:
        parts = [p.strip() for p in line.split("::")]
        for p in reversed(parts):
            p_low = slugify(p)
            for k, v in DEST_CANDIDATES.items():
                if k in p_low:
                    return v
    return "—"

def extract_seeds_from_text(text: str):
    seeds = {}
    for line in text.splitlines():
        if "»" not in line:
            continue
        for m in SEED_PATTERN.finditer(line):
            raw = m.group(1)
            seed = slugify(raw)
            dest = guess_destination_from_line(line)
            # preferimos destino conocido sobre "—"
            if seed not in seeds or (seeds[seed] == "—" and dest != "—"):
                seeds[seed] = dest
    return seeds  # dict seed -> dest

def find_or_create_auto_block(content: str, begin: str, end: str):
    bi = content.find(begin)
    ei = content.find(end)
    if bi == -1 or ei == -1 or ei < bi:
        if not content.endswith("\n"):
            content += "\n"
        content += f"\n{begin}\n{end}\n"
        bi = content.find(begin)
        ei = content.find(end)
    return content, bi, ei

def replace_block(content: str, begin: str, end: str, new_body: str) -> str:
    content, bi, ei = find_or_create_auto_block(content, begin, end)
    head = content[:bi + len(begin)]
    tail = content[ei:]
    body = "\n<!-- auto-generated by qel_indexer.py; do not edit inside this block -->\n" + new_body.strip() + "\n"
    return head + body + tail

def ensure_index_file(path, kind: str, default_seedi: str):
    if os.path.exists(path):
        return
    title = "# Índice de Semillas (auto)" if kind == "seeds" else "# Índice de Rutas Internas (auto)"
    cue_tag = "INDEX-SEMILLAS" if kind == "seeds" else "INDEX-RUTAS"
    sot = "INDICES/SEMILLAS/v1.0" if kind == "seeds" else "INDICES/RUTAS/v1.0"
    txt = textwrap.dedent(f"""\
    cue: "[QEL::ECO[96]::RECALL {default_seedi}-{cue_tag}]"
    SeedI: "{default_seedi}"
    SoT: "{sot}"
    Version: "v1.0"
    Updated: "{today_iso()}"

    {title}

    """)
    if kind == "seeds":
        txt += f"{AUTO_SEEDS_BEGIN}\n{AUTO_SEEDS_END}\n"
    else:
        txt += f"{AUTO_ROUTES_BEGIN}\n{AUTO_ROUTES_END}\n"
    write_text(path, txt)

ROUTE_BLOCK_RE = re.compile(r"<!--\s*ROUTES:(.*?)-->", re.S | re.M)

def parse_routes_from_text(text: str):
    """Lee un bloque embebido:
       <!-- ROUTES:
       R1: /docs/core/QEL_Manual_Operativo.md#sec-0-alcance-y-reglas-de-oro -> /docs/core/QEL_Manual_Operativo.md#sec-3-lamina
       S2: /docs/core/QEL_Libro_Sombras.md#sec-3-casuistica -> /docs/core/QEL_Libro_Sombras.md#sec-2-cue-aurora
       -->
    """
    routes = []
    m = ROUTE_BLOCK_RE.search(text)
    if not m:
        return routes
    block = m.group(1)
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m2 = re.match(r"^([RS]\d+)\s*:\s*(.+)$", line)
        if not m2:
            continue
        label = m2.group(1).strip()
        parts = [p.strip() for p in re.split(r"\s*->\s*", m2.group(2))]
        routes.append((label, parts))
    return routes

def anchor_exists(target_path: str, anchor: str) -> bool:
    if not os.path.exists(target_path):
        return False
    txt = read_text(target_path)
    # los anchors aparecen como "# sec-..." en el texto renderizado
    return anchor in txt

def canonicalize_route_part(part: str, repo_root: str):
    """Normaliza '/docs/...md#anchor' y valida existencia del anchor en el archivo destino."""
    m = re.match(r"^/?(docs/.*?\.md)#([A-Za-z0-9\-\._]+)$", part)
    if not m:
        # si ya viene como [/docs/...#anchor] dejarlo pasar
        m2 = re.match(r"^\[/?(docs/.*?\.md#[A-Za-z0-9\-\._]+)\]$", part)
        if m2:
            part = "/" + m2.group(1)
        return part, True
    rel = m.group(1)
    anchor = m.group(2)
    fs_path = os.path.join(repo_root, rel)
    ok = anchor_exists(fs_path, "#" + anchor) or anchor_exists(fs_path, anchor)
    display = f"/{rel}#{anchor}"
    return display, ok

def render_routes_markdown(routes, repo_root):
    lines = []
    for label, parts in routes:
        rendered = []
        all_ok = True
        for p in parts:
            disp, ok = canonicalize_route_part(p, repo_root)
            rendered.append(disp)
            all_ok = all_ok and ok
        bullet = f"- {label}: " + " → ".join(f"[{r}]({r})" for r in rendered)
        if not all_ok:
            bullet += "  (⚠ uno o más anchors no encontrados)"
        lines.append(bullet)
    return "\n".join(lines)

def update_indices(files, indices_dir, update_modes=("seeds","routes"), default_seedi=None, show_source=False, verbose=False, dry_run=False):
    repo_root = os.getcwd()
    seeds_index = os.path.join(indices_dir, SEEDS_INDEX_BASENAME)
    routes_index = os.path.join(indices_dir, ROUTES_INDEX_BASENAME)

    # SeedI por defecto: del primer archivo que lo tenga, o de env, o fallback
    if not default_seedi:
        for p in files:
            try:
                seedi = extract_seedi_from_text(read_text(p))
            except Exception:
                seedi = None
            if seedi:
                default_seedi = seedi
                break
        if not default_seedi:
            for k in SEEDI_ENV_KEYS:
                if os.environ.get(k):
                    default_seedi = os.environ[k]
                    break
        if not default_seedi:
            default_seedi = "A37-251015"

    if "seeds" in update_modes:
        ensure_index_file(seeds_index, "seeds", default_seedi)
    if "routes" in update_modes:
        ensure_index_file(routes_index, "routes", default_seedi)

    collected_seeds = {}
    collected_routes = []

    for f in files:
        try:
            txt = read_text(f)
        except Exception as e:
            if verbose:
                print(f"[warn] no pude leer {f}: {e}", file=sys.stderr)
            continue

        if "seeds" in update_modes:
            seeds = extract_seeds_from_text(txt)
            if seeds:
                if verbose:
                    print(f"[i] {f}: {len(seeds)} semillas", file=sys.stderr)
                for k,v in seeds.items():
                    collected_seeds[k] = v

        if "routes" in update_modes:
            routes = parse_routes_from_text(txt)
            if routes:
                if verbose:
                    print(f"[i] {f}: {len(routes)} rutas declaradas", file=sys.stderr)
                collected_routes.extend(routes)

    # Escribir Semillas
    if "seeds" in update_modes:
        content = read_text(seeds_index)
        body_lines = []
        for k in sorted(collected_seeds.keys()):
            dest = collected_seeds[k]
            line = f"- »{k} → {dest}"
            if show_source:
                # (opcional) podríamos incluir src, pero lo omitimos para reducir ruido
                pass
            body_lines.append(line)
        new_body = "\n".join(body_lines) if body_lines else "_(sin entradas automáticas aún)_"
        new_content = replace_block(content, AUTO_SEEDS_BEGIN, AUTO_SEEDS_END, new_body)
        if not dry_run:
            write_text(seeds_index, new_content)

    # Escribir Rutas
    if "routes" in update_modes:
        content = read_text(routes_index)
        md_routes = render_routes_markdown(collected_routes, repo_root) if collected_routes else "_(sin rutas automáticas; usa bloque <!-- ROUTES: ... --> en tus docs)_"
        new_content = replace_block(content, AUTO_ROUTES_BEGIN, AUTO_ROUTES_END, md_routes)
        if not dry_run:
            write_text(routes_index, new_content)

def main():
    ap = argparse.ArgumentParser(description="QEL Indexer — mantiene índices de Semillas y Rutas (zonas AUTO) de forma idempotente.")
    ap.add_argument("--file", "-f", action="append", help="Archivo .md a considerar (se puede repetir).")
    ap.add_argument("--all", action="store_true", help="Escanear todos los .md en docs/core/")
    ap.add_argument("--indices-dir", default=INDEX_DIR_DEFAULT, help="Directorio de índices (default: docs/core/indices)")
    ap.add_argument("--update", default="seeds,routes", help="Qué actualizar: seeds,routes (coma)")
    ap.add_argument("--seedI", dest="seedi", default=None, help="SeedI por defecto si no se puede inferir.")
    ap.add_argument("--show-source", action="store_true", help="Mostrar origen de cada semilla (no recomendado para ruido de diffs).")
    ap.add_argument("--verbose", "-v", action="store_true", help="Mensajes informativos.")
    ap.add_argument("--dry-run", action="store_true", help="No escribir, sólo calcular.")
    args = ap.parse_args()

    files = []
    if args.all:
        files.extend(sorted(glob.glob("docs/core/*.md")))
    if args.file:
        files.extend(args.file)
    # desduplicar manteniendo orden
    files = [str(pathlib.Path(p)) for p in dict.fromkeys(files)]

    if not files:
        print("[err] no hay archivos a analizar; usa --file o --all", file=sys.stderr)
        sys.exit(2)

    modes = tuple([m.strip() for m in args.update.split(",") if m.strip() in ("seeds","routes")])
    if not modes:
        print("[err] --update vacío; usa seeds,routes", file=sys.stderr)
        sys.exit(2)

    update_indices(files, args.indices_dir, update_modes=modes, default_seedi=args.seedi, show_source=args.show_source, verbose=args.verbose, dry_run=args.dry_run)

if __name__ == "__main__":
    main()
